spring:
  batch:
    initialize-schema: always
  application:
    name: users-ws
  datasource:
    password: root
    # for windows ##root
    # for mac ##admin123
    testWhileIdle: true
    url: jdbc:mysql://localhost:3306/ipl?useSSL=false
    username: root
    validationQuery: SELECT 1
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
